#服务设置
server:
  #端口号
  port: 8088

spring:
  #动态访问HTML文件
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    suffix: .html

  # 文件上传服务
  servlet:
    # 部分文件限制
    multipart:
      max-request-size: 1000MB # 上传文件总的最大值
      max-file-size: 100MB # 单个文件的最大值

# 文件上传下载默认位置
filepath: D:/file_server/

config:
  path: /Users/zhuli/IdeaProjects/file/version.properties